// src/components/AgentsView.tsx
import { useState } from 'react';
import { Bot, Plus, Server, Settings2, Trash2, X, Save, Check, HelpCircle } from 'lucide-react';
import { SKILLS, KNOWLEDGE_BASES } from '../constants';

export default function AgentsView({ agents, setAgents }: { agents: any[], setAgents: any }) {
  const [editingAgent, setEditingAgent] = useState<any>(null);
  const [formData, setFormData] = useState<any>({});

  const handleEdit = (agent: any) => {
    setFormData({ 
      ...agent, 
      selectedSkills: [...agent.skills], 
      selectedKb: [...agent.knowledge] 
    });
    setEditingAgent(agent.id);
  };

  const handleCreate = () => {
    setFormData({
      id: `agt-custom-${Math.random().toString(36).substr(2, 4)}`,
      name: '自定义专属专家',
      role: 'Worker',
      model: 'gpt-4o',
      temperature: 0.5,
      maxSteps: 5,
      fallback: 'agt-router',
      selectedSkills: [],
      selectedKb: [],
    });
    setEditingAgent('new');
  };

  const handleDelete = (id: string) => {
    if (confirm('确认删除该智能体配置？')) {
      setAgents((prev: any[]) => prev.filter(a => a.id !== id));
      if (editingAgent === id) setEditingAgent(null);
    }
  };

  const handleToggleArr = (arrName: 'selectedSkills' | 'selectedKb', val: string) => {
    setFormData((prev: any) => {
      const arr = prev[arrName] || [];
      if (arr.includes(val)) {
        return { ...prev, [arrName]: arr.filter((x: string) => x !== val) };
      } else {
        return { ...prev, [arrName]: [...arr, val] };
      }
    });
  };

  const handleSave = () => {
    const updatedAgent = {
      ...formData,
      temperature: parseFloat(formData.temperature),
      maxSteps: parseInt(formData.maxSteps, 10),
      skills: formData.selectedSkills,
      knowledge: formData.selectedKb,
    };
    delete updatedAgent.selectedSkills;
    delete updatedAgent.selectedKb;

    if (editingAgent === 'new') {
      setAgents((prev: any[]) => [...prev, updatedAgent]);
    } else {
      setAgents((prev: any[]) => prev.map(a => a.id === editingAgent ? updatedAgent : a));
    }
    setEditingAgent(null);
  };

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-slate-800">智能体配置 (Agent Profiles)</h2>
          <p className="text-slate-500 mt-2">定义调度系统中的核心智能体角色，绑定技能与业务知识库。</p>
        </div>
        <button onClick={handleCreate} className="bg-slate-900 hover:bg-slate-800 text-white px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors shadow-sm">
          <Plus className="w-4 h-4" />
          新建智能体配置
        </button>
      </div>

      <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
        <table className="w-full text-left text-sm whitespace-nowrap">
          <thead className="bg-slate-50 text-slate-600 border-b border-slate-200">
            <tr>
              <th className="px-6 py-4 font-medium">基本信息</th>
              <th className="px-6 py-4 font-medium">模型驱动</th>
              <th className="px-6 py-4 font-medium">编排策略设定</th>
              <th className="px-6 py-4 font-medium">挂载依赖 (Skills / KB)</th>
              <th className="px-6 py-4 font-medium text-right">管理操作</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {agents.map((agent) => (
              <tr key={agent.id} className="hover:bg-slate-50 transition-colors">
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-slate-100 flex items-center justify-center">
                      <Bot className="w-5 h-5 text-slate-600" />
                    </div>
                    <div>
                      <div className="font-medium text-slate-800">{agent.name}</div>
                      <div className="text-xs text-slate-500 font-mono mt-0.5">{agent.id}</div>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4">
                  <div className="flex flex-col gap-1 text-sm">
                    <span className="inline-flex items-center gap-1.5 font-mono text-slate-700 font-medium">
                      <Server className="w-3.5 h-3.5 text-slate-400" />
                      {agent.model}
                    </span>
                    <span className="text-xs text-slate-500">Temp: {agent.temperature}</span>
                  </div>
                </td>
                <td className="px-6 py-4">
                  <div className="text-xs space-y-1.5">
                    <div className="flex items-center gap-2">
                       <span className="w-16 text-slate-500">Max Steps :</span>
                       <span className="font-medium text-slate-800">{agent.maxSteps}</span>
                    </div>
                    <div className="flex items-center gap-2">
                       <span className="w-16 text-slate-500">降级策略  :</span>
                       {agent.fallback ? (
                         <span className="font-mono text-[10px] bg-slate-100 px-1.5 py-0.5 border border-slate-200 rounded">{agent.fallback}</span>
                       ) : (
                         <span className="text-[10px] text-slate-400">无 (终止)</span>
                       )}
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4">
                  <div className="flex max-w-[200px] flex-wrap gap-1.5">
                     {agent.skills.map((s, i) => (
                       <span key={i} className="text-[10px] bg-indigo-50 text-indigo-700 border border-indigo-100 px-2 py-0.5 rounded-full">
                         {s}
                       </span>
                     ))}
                     {agent.knowledge.map((k, i) => (
                       <span key={i} className="text-[10px] bg-amber-50 text-amber-700 border border-amber-100 px-2 py-0.5 rounded-full">
                         {k}
                       </span>
                     ))}
                     {agent.skills.length === 0 && agent.knowledge.length === 0 && (
                       <span className="text-xs text-slate-400 italic">None</span>
                     )}
                  </div>
                </td>
                <td className="px-6 py-4 text-right">
                  <div className="flex justify-end gap-2 text-slate-400">
                    <button onClick={() => handleEdit(agent)} className="p-2 hover:bg-indigo-50 hover:text-indigo-600 rounded-md transition-colors">
                      <Settings2 className="w-4 h-4" />
                    </button>
                    <button onClick={() => handleDelete(agent.id)} className="p-2 hover:bg-red-50 hover:text-red-600 rounded-md transition-colors">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {editingAgent && (
        <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-xl flex flex-col max-h-[90vh]">
            <div className="flex items-center justify-between p-6 border-b border-slate-100 shrink-0">
               <h3 className="text-lg font-bold text-slate-800">{editingAgent === 'new' ? '创建新智能体' : '编辑智能体配置'}</h3>
               <button onClick={() => setEditingAgent(null)} className="text-slate-400 hover:text-slate-600 p-1 rounded-md hover:bg-slate-100">
                 <X className="w-5 h-5" />
               </button>
            </div>
            
            <div className="p-6 overflow-y-auto space-y-5">
               <div className="grid grid-cols-2 gap-5">
                 <div>
                   <label className="block text-xs font-semibold text-slate-600 mb-1.5 uppercase tracking-wider">智能体名称</label>
                   <input type="text" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" />
                 </div>
                 <div>
                   <label className="block text-xs font-semibold text-slate-600 mb-1.5 uppercase tracking-wider">逻辑角色 (Role)</label>
                   <select value={formData.role} onChange={e => setFormData({...formData, role: e.target.value})} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500">
                     <option value="Worker">专家 Worker</option>
                     <option value="Router">路由 Router</option>
                     <option value="Supervisor">主管 Supervisor</option>
                   </select>
                 </div>
               </div>

               <div className="grid grid-cols-3 gap-5">
                 <div>
                   <label className="block text-xs font-semibold text-slate-600 mb-1.5 uppercase tracking-wider">底层模型</label>
                   <input type="text" value={formData.model} onChange={e => setFormData({...formData, model: e.target.value})} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-indigo-500 font-mono" />
                 </div>
                 <div>
                   <label className="block text-xs font-semibold text-slate-600 mb-1.5 uppercase tracking-wider">随机度 (Temp)</label>
                   <input type="number" step="0.1" value={formData.temperature} onChange={e => setFormData({...formData, temperature: e.target.value})} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-indigo-500 font-mono" />
                 </div>
                 <div>
                   <label className="flex items-center gap-1 text-xs font-semibold text-slate-600 mb-1.5 uppercase tracking-wider tooltip-trigger relative group cursor-help">
                     最大步数 (Max Steps)
                     <HelpCircle className="w-3.5 h-3.5" />
                     <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-2 bg-slate-800 text-slate-200 text-[10px] rounded opacity-0 pointer-events-none group-hover:opacity-100 z-10 normal-case tracking-normal">
                       限制大模型在单次决策中调用工具的最大循环次数，防止陷入死循环。
                     </div>
                   </label>
                   <input type="number" value={formData.maxSteps} onChange={e => setFormData({...formData, maxSteps: e.target.value})} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-indigo-500 font-mono" />
                 </div>
               </div>

               <div>
                 <label className="block text-xs font-semibold text-slate-600 mb-2 uppercase tracking-wider">关联技能池 (Skills)</label>
                 <div className="grid grid-cols-2 gap-2 max-h-32 overflow-y-auto p-1">
                   {SKILLS.map(skill => (
                     <label key={skill.id} className="flex items-center gap-2 cursor-pointer p-2 rounded-md hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-colors">
                       <input type="checkbox" className="hidden" checked={formData.selectedSkills?.includes(skill.id) || false} onChange={() => handleToggleArr('selectedSkills', skill.id)} />
                       <div className={`w-4 h-4 rounded flex items-center justify-center shrink-0 ${formData.selectedSkills?.includes(skill.id) ? 'bg-indigo-600' : 'bg-white border border-slate-300'}`}>
                         {formData.selectedSkills?.includes(skill.id) && <Check className="w-3 h-3 text-white" />}
                       </div>
                       <div className="text-sm text-slate-700">{skill.name}</div>
                     </label>
                   ))}
                 </div>
               </div>

               <div>
                 <label className="block text-xs font-semibold text-slate-600 mb-2 uppercase tracking-wider">挂载知识库 (RAG Knowledge Bases)</label>
                 <div className="grid grid-cols-2 gap-2 max-h-32 overflow-y-auto p-1">
                   {KNOWLEDGE_BASES.map(kb => (
                     <label key={kb.id} className="flex items-center gap-2 cursor-pointer p-2 rounded-md hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-colors">
                       <input type="checkbox" className="hidden" checked={formData.selectedKb?.includes(kb.id) || false} onChange={() => handleToggleArr('selectedKb', kb.id)} />
                       <div className={`w-4 h-4 rounded flex items-center justify-center shrink-0 ${formData.selectedKb?.includes(kb.id) ? 'bg-amber-600' : 'bg-white border border-slate-300'}`}>
                         {formData.selectedKb?.includes(kb.id) && <Check className="w-3 h-3 text-white" />}
                       </div>
                       <div className="text-sm text-slate-700">{kb.name}</div>
                     </label>
                   ))}
                 </div>
               </div>
               
               <div>
                 <label className="flex items-center gap-1 text-xs font-semibold text-slate-600 mb-1.5 uppercase tracking-wider cursor-help group relative">
                   降级策略 (Fallback Target)
                   <HelpCircle className="w-3.5 h-3.5" />
                   <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-56 p-2 bg-slate-800 text-slate-200 text-[10px] rounded opacity-0 pointer-events-none group-hover:opacity-100 z-10 normal-case tracking-normal">
                     当当前智能体遭遇异常、或者置信度过低无法解决问题时，接管会话流转的备用目标智能体。(例如转交给人工或降级路由)
                   </div>
                 </label>
                 <select value={formData.fallback || ''} onChange={e => setFormData({...formData, fallback: e.target.value})} className="w-full bg-slate-50 border border-slate-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-indigo-500 font-mono bg-slate-100">
                    <option value="">（无 / 直接终止）</option>
                    {agents.map(a => <option key={a.id} value={a.id}>{a.name} ({a.id})</option>)}
                 </select>
               </div>
            </div>

            <div className="p-6 border-t border-slate-100 flex justify-end gap-3 shrink-0 bg-slate-50 rounded-b-2xl">
               <button onClick={() => setEditingAgent(null)} className="px-5 py-2.5 text-sm font-medium text-slate-600 hover:text-slate-800 transition-colors">取消</button>
               <button onClick={handleSave} className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2.5 rounded-lg text-sm font-medium flex items-center gap-2 transition-colors shadow-sm">
                 <Save className="w-4 h-4" />
                 保存智能体配置
               </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/AgentsView.vue
<template>
  <div class="agents-view">
    <div class="agents-header">
      <div>
        <h2 class="view-title">智能体配置 (Agent Profiles)</h2>
        <p class="view-subtitle">定义调度系统中的核心智能体角色，绑定技能与业务知识库。</p>
      </div>
      <el-button type="primary" @click="handleCreate" dark>
        <el-icon><Plus /></el-icon>
        新建智能体配置
      </el-button>
    </div>

    <el-table :data="agentStore.agents" style="width: 100%;" stripe>
      <el-table-column label="基本信息" min-width="220">
        <template #default="{ row }">
          <div class="agent-info">
            <div class="agent-avatar">
              <el-icon :size="20"><Service /></el-icon>
            </div>
            <div>
              <div class="agent-name">{{ row.name }}</div>
              <div class="agent-id">{{ row.id }}</div>
            </div>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="模型驱动" min-width="160">
        <template #default="{ row }">
          <div class="model-info">
            <span class="model-name">
              <el-icon :size="14"><Monitor /></el-icon>
              {{ row.model }}
            </span>
            <span class="model-temp">Temp: {{ row.temperature }}</span>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="编排策略设定" min-width="180">
        <template #default="{ row }">
          <div class="strategy-info">
            <div class="strategy-row">
              <span class="strategy-label">Max Steps :</span>
              <span class="strategy-value">{{ row.maxSteps }}</span>
            </div>
            <div class="strategy-row">
              <span class="strategy-label">降级策略  :</span>
              <el-tag v-if="row.fallback" size="small" type="info" effect="plain" style="font-family: monospace; font-size: 10px;">{{ row.fallback }}</el-tag>
              <span v-else class="no-fallback">无 (终止)</span>
            </div>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="挂载依赖 (Skills / KB)" min-width="200">
        <template #default="{ row }">
          <div class="deps-tags">
            <el-tag v-for="s in row.skills" :key="s" size="small" effect="plain" type="" style="background: #eef2ff; color: #4338ca; border-color: #c7d2fe; margin: 2px;">{{ s }}</el-tag>
            <el-tag v-for="k in row.knowledge" :key="k" size="small" effect="plain" type="warning" style="margin: 2px;">{{ k }}</el-tag>
            <span v-if="row.skills.length === 0 && row.knowledge.length === 0" class="no-deps">None</span>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="管理操作" width="120" align="right">
        <template #default="{ row }">
          <el-button text @click="handleEdit(row)">
            <el-icon><Setting /></el-icon>
          </el-button>
          <el-button text type="danger" @click="handleDelete(row.id)">
            <el-icon><Delete /></el-icon>
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- Edit Dialog -->
    <el-dialog
      v-model="showDialog"
      :title="editingAgent === 'new' ? '创建新智能体' : '编辑智能体配置'"
      width="600px"
      destroy-on-close
    >
      <el-form label-position="top" class="agent-form">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="智能体名称">
              <el-input v-model="formData.name" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="逻辑角色 (Role)">
              <el-select v-model="formData.role" style="width: 100%;">
                <el-option label="专家 Worker" value="Worker" />
                <el-option label="路由 Router" value="Router" />
                <el-option label="主管 Supervisor" value="Supervisor" />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="20">
          <el-col :span="8">
            <el-form-item label="底层模型">
              <el-input v-model="formData.model" style="font-family: 'JetBrains Mono', monospace;" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="随机度 (Temp)">
              <el-input-number v-model="formData.temperature" :step="0.1" :min="0" :max="2" :precision="1" style="width: 100%;" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="最大步数 (Max Steps)">
              <el-input-number v-model="formData.maxSteps" :min="1" :max="100" style="width: 100%;" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-form-item label="关联技能池 (Skills)">
          <el-checkbox-group v-model="formData.selectedSkills">
            <el-checkbox v-for="skill in skillStore.skills" :key="skill.id" :label="skill.id" :value="skill.id">
              {{ skill.name }}
            </el-checkbox>
          </el-checkbox-group>
        </el-form-item>

        <el-form-item label="挂载知识库 (RAG Knowledge Bases)">
          <el-checkbox-group v-model="formData.selectedKb">
            <el-checkbox v-for="kb in knowledgeStore.knowledgeBases" :key="kb.id" :label="kb.id" :value="kb.id">
              {{ kb.name }}
            </el-checkbox>
          </el-checkbox-group>
        </el-form-item>

        <el-form-item label="降级策略 (Fallback Target)">
          <el-select v-model="formData.fallback" clearable placeholder="（无 / 直接终止）" style="width: 100%;">
            <el-option v-for="a in agentStore.agents" :key="a.id" :label="`${a.name} (${a.id})`" :value="a.id" />
          </el-select>
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="showDialog = false">取消</el-button>
        <el-button type="primary" @click="handleSave">
          <el-icon><Check /></el-icon>
          保存智能体配置
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useAgentStore, useSkillStore, useKnowledgeStore } from '../stores/agent';
import { ElMessageBox } from 'element-plus';

const agentStore = useAgentStore();
const skillStore = useSkillStore();
const knowledgeStore = useKnowledgeStore();

const showDialog = ref(false);
const editingAgent = ref<string | null>(null);
const formData = reactive<any>({});

function handleEdit(agent: any) {
  Object.assign(formData, {
    ...agent,
    selectedSkills: [...agent.skills],
    selectedKb: [...agent.knowledge],
  });
  editingAgent.value = agent.id;
  showDialog.value = true;
}

function handleCreate() {
  Object.assign(formData, {
    id: `agt-custom-${Math.random().toString(36).substr(2, 4)}`,
    name: '自定义专属专家',
    role: 'Worker',
    model: 'gpt-4o',
    temperature: 0.5,
    maxSteps: 5,
    fallback: 'agt-router',
    selectedSkills: [],
    selectedKb: [],
  });
  editingAgent.value = 'new';
  showDialog.value = true;
}

function handleDelete(id: string) {
  ElMessageBox.confirm('确认删除该智能体配置？', '提示', {
    confirmButtonText: '确认',
    cancelButtonText: '取消',
    type: 'warning',
  }).then(() => {
    agentStore.removeAgent(id);
  }).catch(() => {});
}

function handleSave() {
  const updatedAgent = {
    ...formData,
    temperature: parseFloat(formData.temperature),
    maxSteps: parseInt(formData.maxSteps, 10),
    skills: [...formData.selectedSkills],
    knowledge: [...formData.selectedKb],
  };
  delete updatedAgent.selectedSkills;
  delete updatedAgent.selectedKb;

  if (editingAgent.value === 'new') {
    agentStore.addAgent(updatedAgent);
  } else {
    agentStore.updateAgent(editingAgent.value!, updatedAgent);
  }
  showDialog.value = false;
}
</script>

<style scoped>
.agents-view {
  animation: fadeIn 0.5s ease;
}
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}

.agents-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 24px;
}

.agent-info {
  display: flex;
  align-items: center;
  gap: 12px;
}
.agent-avatar {
  width: 40px;
  height: 40px;
  border-radius: 8px;
  background: #f1f5f9;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #475569;
}
.agent-name {
  font-weight: 500;
  color: #1e293b;
}
.agent-id {
  font-size: 12px;
  font-family: 'JetBrains Mono', monospace;
  color: #64748b;
  margin-top: 2px;
}

.model-info {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.model-name {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-family: 'JetBrains Mono', monospace;
  font-weight: 500;
  color: #334155;
  font-size: 13px;
}
.model-temp {
  font-size: 12px;
  color: #64748b;
}

.strategy-info {
  display: flex;
  flex-direction: column;
  gap: 6px;
  font-size: 12px;
}
.strategy-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
.strategy-label {
  width: 80px;
  color: #64748b;
}
.strategy-value {
  font-weight: 500;
  color: #1e293b;
}
.no-fallback {
  font-size: 10px;
  color: #94a3b8;
}

.deps-tags {
  display: flex;
  flex-wrap: wrap;
  max-width: 200px;
}
.no-deps {
  font-size: 12px;
  color: #94a3b8;
  font-style: italic;
}

.agent-form :deep(.el-form-item__label) {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #475569;
}
</style>
