// src/components/KnowledgeView.tsx
import { useState } from 'react';
import { KNOWLEDGE_BASES } from '../constants';
import { Library, CloudUpload, Database, FileText, UploadCloud, Search, ShieldAlert, Plus, X, List, LayoutTemplate } from 'lucide-react';
import { cn } from '../lib/utils';

const TEMPLATES = [
  { id: 'qa', name: 'QA 问答对表格', desc: '适用于结构化审讯记录与标准化咨询', icon: List },
  { id: 'md', name: 'Markdown 规范文档', desc: '适用于法律法规、长文本卷宗提取', icon: FileText },
  { id: 'triple', name: '三元组抽取 (知识图谱)', desc: '(实体-关系-实体) 适用于资金流向追踪', icon: Database },
];

export default function KnowledgeView() {
  const [editingKb, setEditingKb] = useState<any>(null);
  const [selectedTemplate, setSelectedTemplate] = useState('qa');

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 relative h-full flex flex-col">
      <div className="flex items-center justify-between mb-8 shrink-0">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-slate-800">知识库治理 (RAG Vector DB)</h2>
          <p className="text-slate-500 mt-2">管理涉黑案事件、暗语词典等图文案卷的检索策略与模型权限。</p>
        </div>
        <div className="flex items-center gap-3">
          <button className="bg-white border text-slate-700 hover:bg-slate-50 px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors shadow-sm">
            <UploadCloud className="w-4 h-4" />
            批量导入语料
          </button>
          <button onClick={() => setEditingKb('new')} className="bg-slate-900 hover:bg-slate-800 text-white px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors shadow-sm">
            <Plus className="w-4 h-4" />
            可视化新建知识库
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {KNOWLEDGE_BASES.map(kb => (
            <div key={kb.id} className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow group">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-indigo-50 flex items-center justify-center border border-indigo-100">
                    <Library className="w-5 h-5 text-indigo-600" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-slate-800">{kb.name}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[10px] bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded font-mono border border-slate-200">{kb.id}</span>
                      {kb.status === 'active' 
                        ? <span className="text-[10px] text-emerald-600 bg-emerald-50 px-1.5 rounded-full flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>就绪</span>
                        : <span className="text-[10px] text-amber-600 bg-amber-50 px-1.5 rounded-full flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse"></span>向量化中</span>
                      }
                    </div>
                  </div>
                </div>
                <button onClick={() => setEditingKb(kb)} className="opacity-0 group-hover:opacity-100 p-2 hover:bg-slate-100 rounded-md text-slate-600 transition-all" title="可视化构建">
                  <LayoutTemplate className="w-4 h-4" />
                </button>
              </div>

              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <div className="text-xs text-slate-500 mb-1">Embedding 引擎</div>
                  <div className="font-mono text-sm text-slate-800">{kb.embeddingModel}</div>
                </div>
                <div>
                  <div className="text-xs text-slate-500 mb-1">向量后端</div>
                  <div className="flex items-center gap-1.5 text-sm text-slate-800">
                    <Database className="w-3.5 h-3.5 text-slate-400" />
                    {kb.vectorDb}
                  </div>
                </div>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-100">
                <div className="flex items-center gap-2 text-xs text-slate-500 font-medium">
                  <Search className="w-3.5 h-3.5" />
                  <span className="font-mono bg-slate-100 px-1 rounded">{kb.docs.toLocaleString()}</span> 个文档切片
                </div>
                {kb.id.includes('internal') && (
                  <div className="flex items-center gap-1 text-[10px] text-red-600 bg-red-50 px-2 py-1 rounded">
                    <ShieldAlert className="w-3 h-3" />
                    高密级阻断
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
        
        <div className="mt-8 p-5 bg-indigo-50 border border-indigo-100 rounded-xl">
          <h4 className="text-sm font-semibold text-indigo-900">编排指南：动态注入上下文</h4>
          <p className="text-xs text-indigo-700 mt-2 max-w-3xl leading-relaxed">
            知识库独立于智能体运行。编排层 (Orchestrator) 会在运行时将「本轮可用的私有检索列表」动态注入到目标请求中。若检索准确度不足、响应超时或模型置信度较低，系统中配置的降级策略 (<code className="bg-white px-1 rounded">fallbackAgentId</code>) 会自动接管会话，从而避免在司法审判等关键环节中产生幻觉风险。
          </p>
        </div>
      </div>

      {editingKb && (
        <div className="absolute inset-0 bg-white z-20 flex flex-col">
           <div className="flex items-center justify-between p-6 border-b border-slate-100 shrink-0">
             <div>
               <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                 <LayoutTemplate className="w-5 h-5 text-indigo-600" />
                 可视化知识构建与编辑
               </h3>
               <p className="text-sm text-slate-500 mt-1">选择标准化模板结构，快速录入并向量化领域知识。</p>
             </div>
             <button onClick={() => setEditingKb(null)} className="text-slate-400 hover:text-slate-600 p-2 rounded-md hover:bg-slate-100">
               <X className="w-6 h-6" />
             </button>
           </div>
           
           <div className="flex-1 flex overflow-hidden">
             {/* Left Templates Menu */}
             <div className="w-64 border-r border-slate-100 bg-slate-50 p-4 shrink-0 flex flex-col gap-3">
               <label className="text-xs font-semibold text-slate-500 uppercase tracking-widest pl-1">数据切片模板</label>
               {TEMPLATES.map(t => (
                 <button
                   key={t.id}
                   onClick={() => setSelectedTemplate(t.id)}
                   className={cn(
                     "text-left p-3 rounded-lg border transition-all",
                     selectedTemplate === t.id 
                       ? "bg-white border-indigo-200 ring-1 ring-indigo-500 shadow-sm" 
                       : "bg-transparent border-transparent hover:bg-white hover:border-slate-200"
                   )}
                 >
                   <div className="flex items-center gap-2 font-semibold text-slate-800 text-sm">
                     <t.icon className={cn("w-4 h-4", selectedTemplate === t.id ? "text-indigo-600" : "text-slate-400")} />
                     {t.name}
                   </div>
                   <div className="text-[10px] text-slate-500 mt-1.5 leading-snug">{t.desc}</div>
                 </button>
               ))}
             </div>

             {/* Right Editor Area */}
             <div className="flex-1 p-8 overflow-y-auto">
                <div className="max-w-3xl mx-auto space-y-6">
                  {/* Common Meta */}
                  <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm space-y-4">
                     <div>
                       <label className="block text-sm font-medium text-slate-700 mb-1">知识集名称</label>
                       <input type="text" defaultValue={editingKb?.name || ''} placeholder="例如：涉毒黑话1000条" className="w-full border-slate-200 rounded-md py-2 px-3 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 sm:text-sm bg-slate-50" />
                     </div>
                     <div className="grid grid-cols-2 gap-4">
                       <div>
                         <label className="block text-sm font-medium text-slate-700 mb-1">向量模型</label>
                         <select className="w-full border-slate-200 rounded-md py-2 px-3 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 sm:text-sm bg-slate-50">
                           <option>bge-m3-legal (司法专精)</option>
                           <option>text-embedding-3-small</option>
                           <option>bge-m3-finance (经侦专精)</option>
                         </select>
                       </div>
                       <div>
                         <label className="block text-sm font-medium text-slate-700 mb-1">向量后端 (Vector DB)</label>
                         <select className="w-full border-slate-200 rounded-md py-2 px-3 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 sm:text-sm bg-slate-50">
                           <option>纯向量检索: Milvus</option>
                           <option>纯向量检索: Qdrant</option>
                           <option>纯向量检索: Weaviate</option>
                           <option>纯向量检索: FAISS</option>
                           <option>混合检索: Milvus + Elasticsearch</option>
                           <option>内置轻量级库 (Dify/MaxKB版)</option>
                         </select>
                       </div>
                       <div>
                         <label className="block text-sm font-medium text-slate-700 mb-1">分块策略 (Chunking)</label>
                         <select className="w-full border-slate-200 rounded-md py-2 px-3 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 sm:text-sm bg-slate-50">
                           <option>按语义与模板结构分块</option>
                           <option>固定 512 Tokens</option>
                           <option>按段落或换行</option>
                         </select>
                       </div>
                     </div>
                  </div>

                  {/* Template Editor Wrapper */}
                  <div className="bg-white border border-slate-200 rounded-xl flex flex-col shadow-sm overflow-hidden">
                    <div className="bg-slate-50 px-4 py-3 border-b border-slate-200 flex justify-between items-center">
                      <span className="text-sm font-semibold text-slate-700 flex items-center gap-2">
                         <LayoutTemplate className="w-4 h-4" /> 混合知识解析录入
                      </span>
                      <button className="text-xs text-indigo-600 font-medium hover:text-indigo-800">上传源文件</button>
                    </div>
                    
                    <div className="bg-slate-50/50 p-4 border-b border-slate-100">
                      <p className="text-xs text-slate-500 mb-2 font-semibold">支持的文件类型：</p>
                      <div className="flex flex-wrap gap-2 text-[10px]">
                        <span className="px-2 py-1 bg-white border border-slate-200 rounded-md text-slate-600">.md, .txt, .pdf, .docx, .html, .pptx</span>
                        <span className="px-2 py-1 bg-white border border-slate-200 rounded-md text-slate-600">.csv, .xlsx, .jsonl</span>
                        <span className="px-2 py-1 bg-white border border-slate-200 rounded-md text-slate-600">.jpg, .png (需开启多模态)</span>
                      </div>
                    </div>

                    <div className="p-5">
                       {selectedTemplate === 'qa' && (
                         <div className="space-y-4">
                           <div className="grid grid-cols-12 gap-2 text-xs font-semibold text-slate-500 px-2">
                             <div className="col-span-5">问题 / 术语 (Question)</div>
                             <div className="col-span-7">解答 / 定义 (Answer)</div>
                           </div>
                           {[1,2,3].map(i => (
                             <div key={i} className="grid grid-cols-12 gap-2">
                               <input placeholder={i === 1 ? '什么是“开板”？' : ''} className="col-span-5 text-sm border-slate-200 px-3 py-2 rounded focus:outline-none shadow-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 bg-slate-50" />
                               <textarea rows={1} placeholder={i === 1 ? '指吸食冰毒后，将残留在锡纸上的物质收集...' : ''} className="col-span-7 text-sm border-slate-200 px-3 py-2 rounded focus:outline-none shadow-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 resize-none bg-slate-50"></textarea>
                             </div>
                           ))}
                           <button className="text-sm text-slate-500 hover:text-indigo-600 flex items-center gap-1 py-2 font-medium">
                             <Plus className="w-4 h-4" /> 新增一条 QA 记录
                           </button>
                         </div>
                       )}

                       {selectedTemplate === 'md' && (
                         <div className="h-64">
                           <textarea className="w-full h-full p-4 border border-slate-200 rounded-lg text-sm bg-slate-50 font-mono focus:outline-none focus:bg-white transition-colors focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" placeholder="# 第一章 总则\n\n## 第一条 目的\n为了明确电子数据取证标准..."></textarea>
                         </div>
                       )}

                       {selectedTemplate === 'triple' && (
                         <div className="space-y-4">
                           <div className="grid grid-cols-12 gap-2 text-xs font-semibold text-slate-500 px-2 text-center">
                             <div className="col-span-4">源实体 (Subject)</div>
                             <div className="col-span-3">关系 (Predicate)</div>
                             <div className="col-span-4">目标实体 (Object)</div>
                           </div>
                           {[1,2].map(i => (
                             <div key={i} className="grid grid-cols-12 gap-2 items-center">
                               <input placeholder={i === 1 ? '张三 (嫌疑人)' : ''} className="col-span-4 text-sm px-3 py-2 border-slate-200 rounded focus:outline-none shadow-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-center bg-blue-50/50" />
                               <input placeholder={i === 1 ? '转账控制' : ''} className="col-span-3 text-sm px-3 py-2 border-slate-200 rounded focus:outline-none shadow-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-center font-mono text-slate-600 bg-slate-50" />
                               <input placeholder={i === 1 ? '李四账户 (尾号3921)' : ''} className="col-span-4 text-sm px-3 py-2 border-slate-200 rounded focus:outline-none shadow-sm focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 text-center bg-emerald-50/50" />
                               <button className="col-span-1 border-none text-slate-400 hover:text-red-500 flex justify-center"><X className="w-4 h-4" /></button>
                             </div>
                           ))}
                           <button className="text-sm text-slate-500 hover:text-indigo-600 flex items-center gap-1 py-2 font-medium">
                             <Plus className="w-4 h-4" /> 新增三元组
                           </button>
                         </div>
                       )}
                    </div>
                  </div>

                  <div className="flex justify-end gap-3 pt-4">
                    <button onClick={() => setEditingKb(null)} className="px-6 py-2 border border-slate-200 rounded-md text-slate-600 font-medium hover:bg-slate-50">返回列表</button>
                    <button onClick={() => setEditingKb(null)} className="px-6 py-2 bg-indigo-600 text-white rounded-md font-medium hover:bg-indigo-700 shadow-sm flex items-center gap-2">
                       <Database className="w-4 h-4" />
                       保存并执行入库向量化任务
                    </button>
                  </div>
                </div>
             </div>
           </div>
        </div>
      )}
    </div>
  );
}

// src/components/KnowledgeView.vue
<template>
  <div class="knowledge-view">
    <div class="kb-header">
      <div>
        <h2 class="view-title">知识库治理 (RAG Vector DB)</h2>
        <p class="view-subtitle">管理涉黑案事件、暗语词典等图文案卷的检索策略与模型权限。</p>
      </div>
      <div class="kb-actions">
        <el-button>
          <el-icon><Upload /></el-icon>
          批量导入语料
        </el-button>
        <el-button type="primary" dark @click="openEditor('new')">
          <el-icon><Plus /></el-icon>
          可视化新建知识库
        </el-button>
      </div>
    </div>

    <el-row :gutter="16">
      <el-col :span="12" v-for="kb in knowledgeStore.knowledgeBases" :key="kb.id">
        <div class="kb-card">
          <div class="kb-top">
            <div class="kb-identity">
              <div class="kb-icon">
                <el-icon :size="20"><Reading /></el-icon>
              </div>
              <div>
                <h3>{{ kb.name }}</h3>
                <div class="kb-badges">
                  <span class="type-tag">{{ kb.id }}</span>
                  <span v-if="kb.status === 'active'" class="status-badge active">
                    <span class="status-dot-inline"></span>就绪
                  </span>
                  <span v-else class="status-badge syncing">
                    <span class="status-dot-inline pulse-dot"></span>向量化中
                  </span>
                </div>
              </div>
            </div>
            <el-button text class="edit-btn" @click="openEditor(kb)">
              <el-icon><Grid /></el-icon>
            </el-button>
          </div>

          <div class="kb-meta">
            <div>
              <div class="meta-label">Embedding 引擎</div>
              <div class="meta-value mono">{{ kb.embeddingModel }}</div>
            </div>
            <div>
              <div class="meta-label">向量后端</div>
              <div class="meta-value">
                <el-icon :size="14" style="color: #94a3b8; margin-right: 4px;"><Coin /></el-icon>
                {{ kb.vectorDb }}
              </div>
            </div>
          </div>

          <div class="kb-footer">
            <div class="kb-docs">
              <el-icon :size="14"><Search /></el-icon>
              <span class="type-tag">{{ kb.docs.toLocaleString() }}</span>
              <span>个文档切片</span>
            </div>
            <div v-if="kb.id.includes('internal')" class="kb-restricted">
              <el-icon :size="12"><WarningFilled /></el-icon>
              高密级阻断
            </div>
          </div>
        </div>
      </el-col>
    </el-row>

    <!-- Guide -->
    <div class="kb-guide">
      <h4>编排指南：动态注入上下文</h4>
      <p>
        知识库独立于智能体运行。编排层 (Orchestrator) 会在运行时将「本轮可用的私有检索列表」动态注入到目标请求中。若检索准确度不足、响应超时或模型置信度较低，系统中配置的降级策略 (<code>fallbackAgentId</code>) 会自动接管会话，从而避免在司法审判等关键环节中产生幻觉风险。
      </p>
    </div>

    <!-- Editor Drawer -->
    <el-drawer
      v-model="showEditor"
      title="可视化知识构建与编辑"
      direction="rtl"
      size="80%"
    >
      <template #header>
        <div class="drawer-header">
          <h3>
            <el-icon style="color: #4f46e5; margin-right: 8px;"><Grid /></el-icon>
            可视化知识构建与编辑
          </h3>
          <p>选择标准化模板结构，快速录入并向量化领域知识。</p>
        </div>
      </template>

      <div class="editor-layout">
        <!-- Left Templates -->
        <div class="template-sidebar">
          <label class="template-label">数据切片模板</label>
          <div
            v-for="t in TEMPLATES"
            :key="t.id"
            :class="['template-btn', { active: selectedTemplate === t.id }]"
            @click="selectedTemplate = t.id"
          >
            <div class="template-name">
              <el-icon :size="16" :color="selectedTemplate === t.id ? '#4f46e5' : '#94a3b8'"><component :is="t.icon" /></el-icon>
              {{ t.name }}
            </div>
            <div class="template-desc">{{ t.desc }}</div>
          </div>
        </div>

        <!-- Right Editor -->
        <div class="editor-main">
          <div class="editor-inner">
            <!-- Meta -->
            <div class="view-card" style="margin-bottom: 24px;">
              <el-form label-position="top">
                <el-form-item label="知识集名称">
                  <el-input v-model="editingKb.name" placeholder="例如：涉毒黑话1000条" />
                </el-form-item>
                <el-row :gutter="16">
                  <el-col :span="8">
                    <el-form-item label="向量模型">
                      <el-select v-model="editingKb.embeddingModel" style="width: 100%;">
                        <el-option label="bge-m3-legal (司法专精)" value="bge-m3-legal" />
                        <el-option label="text-embedding-3-small" value="text-embedding-3-small" />
                        <el-option label="bge-m3-finance (经侦专精)" value="bge-m3-finance" />
                      </el-select>
                    </el-form-item>
                  </el-col>
                  <el-col :span="8">
                    <el-form-item label="向量后端 (Vector DB)">
                      <el-select style="width: 100%;">
                        <el-option label="纯向量检索: Milvus" />
                        <el-option label="纯向量检索: Qdrant" />
                        <el-option label="纯向量检索: Weaviate" />
                        <el-option label="纯向量检索: FAISS" />
                        <el-option label="混合检索: Milvus + Elasticsearch" />
                        <el-option label="内置轻量级库 (Dify/MaxKB版)" />
                      </el-select>
                    </el-form-item>
                  </el-col>
                  <el-col :span="8">
                    <el-form-item label="分块策略 (Chunking)">
                      <el-select style="width: 100%;">
                        <el-option label="按语义与模板结构分块" />
                        <el-option label="固定 512 Tokens" />
                        <el-option label="按段落或换行" />
                      </el-select>
                    </el-form-item>
                  </el-col>
                </el-row>
              </el-form>
            </div>

            <!-- Template Editor -->
            <div class="view-card" style="overflow: hidden;">
              <div class="editor-toolbar">
                <span><el-icon><Grid /></el-icon> 混合知识解析录入</span>
                <el-button text type="primary" size="small">上传源文件</el-button>
              </div>
              <div class="editor-file-types">
                <span class="file-type-label">支持的文件类型：</span>
                <div class="file-types">
                  <el-tag size="small" effect="plain" v-for="ft in fileTypes" :key="ft">{{ ft }}</el-tag>
                </div>
              </div>
              <div class="editor-content">
                <!-- QA Template -->
                <div v-if="selectedTemplate === 'qa'" class="qa-editor">
                  <div class="qa-header">
                    <span class="qa-col">问题 / 术语 (Question)</span>
                    <span class="qa-col-wide">解答 / 定义 (Answer)</span>
                  </div>
                  <div v-for="i in 3" :key="i" class="qa-row">
                    <el-input :placeholder="i === 1 ? qaPlaceholderQ : ''" />
                    <el-input type="textarea" :rows="1" :placeholder="i === 1 ? qaPlaceholderA : ''" />
                  </div>
                  <el-button text style="margin-top: 8px;">
                    <el-icon><Plus /></el-icon> 新增一条 QA 记录
                  </el-button>
                </div>

                <!-- MD Template -->
                <div v-if="selectedTemplate === 'md'" class="md-editor">
                  <el-input type="textarea" :rows="10" :placeholder="mdPlaceholder" style="font-family: 'JetBrains Mono', monospace;" />
                </div>

                <!-- Triple Template -->
                <div v-if="selectedTemplate === 'triple'" class="triple-editor">
                  <div class="triple-header">
                    <span>源实体 (Subject)</span>
                    <span>关系 (Predicate)</span>
                    <span>目标实体 (Object)</span>
                  </div>
                  <div v-for="i in 2" :key="i" class="triple-row">
                    <el-input :placeholder="i === 1 ? triplePlaceholderS : ''" />
                    <el-input :placeholder="i === 1 ? triplePlaceholderP : ''" style="font-family: 'JetBrains Mono', monospace;" />
                    <el-input :placeholder="i === 1 ? triplePlaceholderO : ''" />
                    <el-button text type="danger" :icon="Close" size="small" />
                  </div>
                  <el-button text style="margin-top: 8px;">
                    <el-icon><Plus /></el-icon> 新增三元组
                  </el-button>
                </div>
              </div>
            </div>

            <div class="editor-footer">
              <el-button @click="showEditor = false">返回列表</el-button>
              <el-button type="primary" @click="showEditor = false">
                <el-icon><Coin /></el-icon>
                保存并执行入库向量化任务
              </el-button>
            </div>
          </div>
        </div>
      </div>
    </el-drawer>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useKnowledgeStore } from '../stores/agent';
import { Close } from '@element-plus/icons-vue';

const knowledgeStore = useKnowledgeStore();

const TEMPLATES = [
  { id: 'qa', name: 'QA 问答对表格', desc: '适用于结构化审讯记录与标准化咨询', icon: 'List' },
  { id: 'md', name: 'Markdown 规范文档', desc: '适用于法律法规、长文本卷宗提取', icon: 'Document' },
  { id: 'triple', name: '三元组抽取 (知识图谱)', desc: '(实体-关系-实体) 适用于资金流向追踪', icon: 'Coin' },
];

const fileTypes = ['.md, .txt, .pdf, .docx, .html, .pptx', '.csv, .xlsx, .jsonl', '.jpg, .png (需开启多模态)'];

const showEditor = ref(false);
const selectedTemplate = ref('qa');
const editingKb = reactive<any>({ name: '', embeddingModel: 'bge-m3-legal' });
const qaPlaceholderQ = '什么是「开板」？';
const qaPlaceholderA = '指吸食冰毒后，将残留在锡纸上的物质收集...';
const mdPlaceholder = '# 第一章 总则\n\n## 第一条 目的\n为了明确电子数据取证标准...';
const triplePlaceholderS = '张三 (嫌疑人)';
const triplePlaceholderP = '转账控制';
const triplePlaceholderO = '李四账户 (尾号3921)';

function openEditor(kb: any) {
  if (kb === 'new') {
    Object.assign(editingKb, { name: '', embeddingModel: 'bge-m3-legal' });
  } else {
    Object.assign(editingKb, { ...kb });
  }
  showEditor.value = true;
}
</script>

<style scoped>
.knowledge-view {
  height: 100%;
  display: flex;
  flex-direction: column;
  animation: fadeIn 0.5s ease;
}
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}

.kb-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 24px;
  flex-shrink: 0;
}
.kb-actions {
  display: flex;
  gap: 12px;
}

.kb-card {
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 1px 2px rgba(0,0,0,0.04);
  margin-bottom: 16px;
  transition: box-shadow 0.2s;
}
.kb-card:hover {
  box-shadow: 0 4px 12px rgba(0,0,0,0.08);
}

.kb-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 16px;
}
.kb-identity {
  display: flex;
  align-items: center;
  gap: 12px;
}
.kb-icon {
  width: 40px;
  height: 40px;
  border-radius: 8px;
  background: #eef2ff;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid #c7d2fe;
  color: #4f46e5;
}
.kb-identity h3 {
  font-weight: 600;
  color: #1e293b;
  font-size: 14px;
  margin: 0;
}
.kb-badges {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 4px;
}
.status-dot-inline {
  display: inline-block;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #10b981;
  margin-right: 4px;
}
.edit-btn {
  opacity: 0;
  transition: opacity 0.2s;
}
.kb-card:hover .edit-btn {
  opacity: 1;
}

.kb-meta {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  margin-bottom: 16px;
}
.meta-label {
  font-size: 12px;
  color: #64748b;
  margin-bottom: 4px;
}
.meta-value {
  font-size: 13px;
  color: #1e293b;
  display: flex;
  align-items: center;
}
.meta-value.mono {
  font-family: 'JetBrains Mono', monospace;
}

.kb-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-top: 16px;
  border-top: 1px solid #f1f5f9;
}
.kb-docs {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: #64748b;
  font-weight: 500;
}
.kb-restricted {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 10px;
  color: #dc2626;
  background: #fee2e2;
  padding: 4px 8px;
  border-radius: 4px;
}

.kb-guide {
  margin-top: 32px;
  padding: 20px;
  background: #eef2ff;
  border: 1px solid #c7d2fe;
  border-radius: 12px;
}
.kb-guide h4 {
  font-size: 13px;
  font-weight: 600;
  color: #312e81;
  margin: 0 0 8px;
}
.kb-guide p {
  font-size: 12px;
  color: #3730a3;
  line-height: 1.6;
  max-width: 768px;
}
.kb-guide code {
  background: #fff;
  padding: 1px 6px;
  border-radius: 4px;
}

/* Drawer */
.drawer-header h3 {
  font-size: 18px;
  font-weight: 700;
  color: #1e293b;
  display: flex;
  align-items: center;
  margin: 0;
}
.drawer-header p {
  font-size: 13px;
  color: #64748b;
  margin: 4px 0 0;
}

.editor-layout {
  display: flex;
  height: 100%;
  overflow: hidden;
}
.template-sidebar {
  width: 256px;
  border-right: 1px solid #f1f5f9;
  background: #f8fafc;
  padding: 16px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.template-label {
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: #64748b;
  font-weight: 600;
  padding-left: 4px;
}
.template-btn {
  text-align: left;
  padding: 12px;
  border-radius: 8px;
  border: 1px solid transparent;
  cursor: pointer;
  transition: all 0.2s;
}
.template-btn:hover {
  background: #fff;
  border-color: #e2e8f0;
}
.template-btn.active {
  background: #fff;
  border-color: #c7d2fe;
  box-shadow: 0 0 0 1px #818cf8;
}
.template-name {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
  font-size: 13px;
  color: #1e293b;
}
.template-desc {
  font-size: 10px;
  color: #64748b;
  margin-top: 6px;
  line-height: 1.4;
}

.editor-main {
  flex: 1;
  padding: 32px;
  overflow-y: auto;
}
.editor-inner {
  max-width: 768px;
  margin: 0 auto;
}

.editor-toolbar {
  background: #f8fafc;
  padding: 12px 16px;
  border-bottom: 1px solid #e2e8f0;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 13px;
  font-weight: 600;
  color: #334155;
}
.editor-file-types {
  background: rgba(248, 250, 252, 0.5);
  padding: 16px;
  border-bottom: 1px solid #f1f5f9;
}
.file-type-label {
  font-size: 12px;
  color: #64748b;
  font-weight: 600;
  display: block;
  margin-bottom: 8px;
}
.file-types {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
.editor-content {
  padding: 20px;
}

/* QA Editor */
.qa-header {
  display: grid;
  grid-template-columns: 5fr 7fr;
  gap: 8px;
  font-size: 12px;
  font-weight: 600;
  color: #64748b;
  padding: 0 8px;
}
.qa-row {
  display: grid;
  grid-template-columns: 5fr 7fr;
  gap: 8px;
  margin-top: 8px;
}

/* Triple Editor */
.triple-header {
  display: grid;
  grid-template-columns: 4fr 3fr 4fr;
  gap: 8px;
  font-size: 12px;
  font-weight: 600;
  color: #64748b;
  text-align: center;
  padding: 0 8px;
}
.triple-row {
  display: grid;
  grid-template-columns: 4fr 3fr 4fr auto;
  gap: 8px;
  align-items: center;
  margin-top: 8px;
}

.editor-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding-top: 16px;
}
</style>
