// src/components/SkillsView.vue
<template>
  <div class="skills-view">
    <div class="skills-header">
      <div>
        <h2 class="view-title">插拔式 Skill 库</h2>
        <p class="view-subtitle">将外部 API、脚本或内部 Java SPI 封装为原子能力供智能体调用。</p>
      </div>
      <el-button type="primary" dark>
        <el-icon><Plus /></el-icon>
        注册 Skill
      </el-button>
    </div>

    <el-row :gutter="16">
      <el-col :span="12" v-for="skill in skillStore.skills" :key="skill.id">
        <div class="skill-card">
          <div class="skill-top">
            <div class="skill-identity">
              <div class="skill-icon">
                <el-icon :size="20"><SetUp /></el-icon>
              </div>
              <div>
                <h3>{{ skill.name }}</h3>
                <span class="skill-id">{{ skill.id }}</span>
              </div>
            </div>
            <span :class="['status-badge', skill.status === 'active' ? 'active' : 'warning']">
              {{ skill.status }}
            </span>
          </div>

          <div class="skill-meta">
            <div class="meta-item">
              <span class="meta-label">接入类型</span>
              <span class="meta-value">{{ skill.type }}</span>
            </div>
            <div class="meta-item">
              <span class="meta-label">提供方 / API</span>
              <span class="meta-value">{{ skill.provider }}</span>
            </div>
            <div class="meta-item">
              <span class="meta-label">鉴权方式</span>
              <span class="meta-value">{{ skill.auth }}</span>
            </div>
          </div>

          <div class="skill-action">
            <el-button text type="primary" size="small">配置鉴权参数 →</el-button>
          </div>
        </div>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { useSkillStore } from '../stores/agent';

const skillStore = useSkillStore();
</script>

<style scoped>
.skills-view {
  animation: fadeIn 0.5s ease;
}
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(8px); }
  to { opacity: 1; transform: translateY(0); }
}

.skills-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 24px;
}

.skill-card {
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 1px 2px rgba(0,0,0,0.04);
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-bottom: 16px;
}

.skill-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
}
.skill-identity {
  display: flex;
  align-items: center;
  gap: 12px;
}
.skill-icon {
  padding: 8px;
  background: #f1f5f9;
  border-radius: 8px;
  color: #475569;
}
.skill-identity h3 {
  font-weight: 600;
  color: #1e293b;
  font-size: 14px;
  margin: 0;
}
.skill-id {
  font-size: 12px;
  font-family: 'JetBrains Mono', monospace;
  color: #64748b;
  margin-top: 2px;
  display: block;
}

.skill-meta {
  padding-top: 16px;
  border-top: 1px dashed #f1f5f9;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 16px;
  font-size: 12px;
}
.meta-label {
  display: block;
  color: #64748b;
  margin-bottom: 4px;
}
.meta-value {
  font-weight: 500;
  color: #1e293b;
}

.skill-action {
  margin-top: 8px;
}
</style>

// src/components/SkillsView.tsx
import { SKILLS } from '../constants';
import { Box, Plus, Wrench } from 'lucide-react';
import { cn } from '../lib/utils';

export default function SkillsView() {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-slate-800">插拔式 Skill 库</h2>
          <p className="text-slate-500 mt-2">将外部 API、脚本或内部 Java SPI 封装为原子能力供智能体调用。</p>
        </div>
        <button className="bg-slate-900 hover:bg-slate-800 text-white px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors">
          <Plus className="w-4 h-4" />
          注册 Skill
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {SKILLS.map((skill) => (
          <div key={skill.id} className="p-5 bg-white border border-slate-200 rounded-xl shadow-sm flex flex-col gap-4">
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-slate-100 rounded-lg">
                  <Wrench className="w-5 h-5 text-slate-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-slate-800">{skill.name}</h3>
                  <p className="text-xs text-slate-500 font-mono mt-0.5">{skill.id}</p>
                </div>
              </div>
              <span className={cn(
                "text-[10px] uppercase font-bold tracking-wider px-2 py-1 rounded",
                skill.status === 'active' ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"
              )}>
                {skill.status}
              </span>
            </div>
            
            <div className="pt-4 border-t border-dashed border-slate-100 grid grid-cols-2 gap-4 text-xs">
              <div>
                <span className="text-slate-500 block mb-1">接入类型</span>
                <span className="font-medium text-slate-800">{skill.type}</span>
              </div>
              <div>
                <span className="text-slate-500 block mb-1">提供方 / API</span>
                <span className="font-medium text-slate-800">{skill.provider}</span>
              </div>
              <div>
                <span className="text-slate-500 block mb-1">鉴权方式</span>
                <span className="font-medium text-slate-800">{skill.auth}</span>
              </div>
            </div>
            
            <div className="mt-2 flex">
              <button className="text-sm font-medium text-indigo-600 hover:text-indigo-700">配置鉴权参数 →</button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
